version = 0.1
[default.deploy.parameters]
stack_name = "a2b-ml-service-api-2"
resolve_s3 = true
s3_prefix = "a2b-ml-service-api-2"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
disable_rollback = true
20250504\" ModelObjectKey=\"models/dt_modparameter_overrides = "ModelBucketName=\"a2b-ml-artifacts-kn-euw2-el_v1.joblib\" LambdaMemorySize=\"512\" LambdaTimeout=\"30\""
image_repositories = []
